  language: ruby
rvm:
  - 1.9.2
before_script:
  - bundle install
  - cp spec/config/database.yml config/database.yml; bundle exec rake db:migrate
  - cp spec/config/app_config.yml config/app_config.yml
script: "bundle exec rspec spec"
notifications:
  email:
    - me@benhughes.name

