development:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  AWS_BUCKET:
  MEETUP_API_KEY: 28593fc521913722bc11a60253a29
test:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  AWS_BUCKET:
  MEETUP_API_KEY: 28593fc521913722bc11a60253a29
